# Generated by Django 5.2.6 on 2025-09-23 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='residentes/')),
                ('datos_biometricos', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('R', 'Residente'), ('V', 'Visitante'), ('D', 'Delivery')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='accesos.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_persona', models.CharField(choices=[('R', 'Residente'), ('V', 'Visitante'), ('D', 'Delivery')], max_length=1)),
                ('tipo_verificacion', models.CharField(choices=[('F', 'Facial'), ('C', 'Credencial'), ('M', 'Manual')], max_length=1)),
                ('persona_id', models.IntegerField()),
                ('exitoso', models.BooleanField()),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('tipo_acceso', models.CharField(choices=[('P', 'Peatonal'), ('V', 'Vehicular')], max_length=1)),
                ('fecha_hora', models.DateTimeField()),
                ('tiempo_estimado', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('completado', models.BooleanField(default=False)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_autorizados', to='accesos.residente')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='visitantes/')),
                ('tipo_acceso', models.CharField(choices=[('P', 'Peatonal'), ('V', 'Vehicular')], max_length=1)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes_autorizados', to='accesos.residente')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.vehiculo')),
            ],
        ),
    ]
