# Generated by Django 5.2.6 on 2025-09-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_configuraciones_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.JSONField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=10)),
                ('torre', models.CharField(blank=True, max_length=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('UTILIZADA', 'Utilizada')], default='ACTIVA', max_length=10)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('qr_image', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_otorgadas', to='accesos.residente')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='accesos.visitante')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='accesos.familia')),
            ],
        ),
        migrations.AddField(
            model_name='residente',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='accesos.familia'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTORIZACION_CREADA', 'Nueva Autorización'), ('AUTORIZACION_EXTENDIDA', 'Autorización Extendida'), ('AUTORIZACION_VENCIDA', 'Autorización Vencida'), ('AUTORIZACION_UTILIZADA', 'Autorización Utilizada'), ('ACCESO_DENEGADO', 'Acceso Denegado')], max_length=50)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accesos.residente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
