# Generated by Django 5.2.6 on 2025-09-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_configuracionacceso_familia_autorizacionvisita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='tipo',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('FAMILIAR', 'Familiar')], default='FAMILIAR', max_length=10),
        ),
    ]
