# Generated by Django 5.2.6 on 2025-09-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_residente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='puede_abrir_porton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='puede_abrir_puerta',
            field=models.BooleanField(default=False),
        ),
    ]
