# Generated by Django 5.2.6 on 2025-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_residente_puede_abrir_porton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionvisita',
            name='dentro',
            field=models.BooleanField(default=False, help_text='Indica si el visitante se encuentra dentro actualmente'),
        ),
        migrations.AddField(
            model_name='autorizacionvisita',
            name='entradas_consumidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autorizacionvisita',
            name='entradas_permitidas',
            field=models.IntegerField(default=1, help_text='Cantidad de ingresos permitidos (cada uno con su salida).'),
        ),
    ]
