# Generated by Django 5.2.6 on 2025-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0006_autorizacionvisita_dentro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='puede_generar_qr_peatonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='puede_generar_qr_vehicular',
            field=models.BooleanField(default=False),
        ),
    ]
