# Generated by Django 5.2.6 on 2025-09-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0009_seed_areas_comunes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unidadarea',
            unique_together=None,
        ),
        # Eliminar primero las dependencias (reservas) y luego las entidades base
        migrations.DeleteModel(
            name='ReservaArea',
        ),
        migrations.DeleteModel(
            name='TurnoArea',
        ),
        migrations.DeleteModel(
            name='UnidadArea',
        ),
        migrations.DeleteModel(
            name='AreaComun',
        ),
    ]
