# Generated by Django 5.2.6 on 2025-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0010_remove_turnoarea_area_remove_unidadarea_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
