# Generated by Django 5.2.6 on 2025-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0011_alter_visitante_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='puede_reservar_area',
            field=models.BooleanField(default=True),
        ),
    ]
