# Generated by Django 5.2.6 on 2025-09-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0012_residente_puede_reservar_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='puede_reservar_area',
        ),
    ]
