# Generated by Django 5.2.6 on 2025-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0013_remove_residente_puede_reservar_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='puede_reservar_areas',
            field=models.BooleanField(default=True, help_text='Puede crear reservas en áreas comunes'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='puede_abrir_porton',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='puede_abrir_puerta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='puede_generar_qr_peatonal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='puede_generar_qr_vehicular',
            field=models.BooleanField(default=True),
        ),
    ]
