# Generated by Django 5.2.6 on 2025-09-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0014_residente_puede_reservar_areas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
