# Generated by Django 5.2.6 on 2025-12-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_configuraciones_iniciales'),
        ('accesos', '0015_delete_notificacion'),
    ]

    operations = [
    ]
