steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--build-arg', 'VITE_API_URL=$_VITE_API_URL', '-t', '$_IMAGE_NAME', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_IMAGE_NAME' ]
images:
  - '$_IMAGE_NAME'
