# Generated by Django 5.2.6 on 2025-09-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0015_delete_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTORIZACION_CREADA', 'Nueva Autorización'), ('AUTORIZACION_EXTENDIDA', 'Autorización Extendida'), ('AUTORIZACION_VENCIDA', 'Autorización Vencida'), ('AUTORIZACION_UTILIZADA', 'Autorización Utilizada'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('EMERGENCIA', 'Emergencia'), ('MULTA', 'Multa'), ('ACTIVIDAD', 'Actividad'), ('AVISO', 'Aviso General')], max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accesos.residente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
