# Generated by Django 5.2.6 on 2025-09-30 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0015_delete_notificacion'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accesos.residente'),
        ),
        migrations.CreateModel(
            name='NotificacionCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTORIZACION_CREADA', 'Nueva Autorización'), ('AUTORIZACION_EXTENDIDA', 'Autorización Extendida'), ('AUTORIZACION_VENCIDA', 'Autorización Vencida'), ('AUTORIZACION_UTILIZADA', 'Autorización Utilizada'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('EMERGENCIA', 'Emergencia'), ('MULTA', 'Multa'), ('ACTIVIDAD', 'Actividad'), ('AVISO', 'Aviso General')], max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('incluir_admins', models.BooleanField(default=False, help_text='Incluir usuarios administradores como destinatarios')),
                ('incluir_todos_residentes', models.BooleanField(default=False, help_text='Enviar a todos los residentes activos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias_creadas', to=settings.AUTH_USER_MODEL)),
                ('familias', models.ManyToManyField(blank=True, related_name='campanias', to='accesos.familia')),
                ('residentes', models.ManyToManyField(blank=True, related_name='campanias', to='accesos.residente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='notificaciones.notificacioncampania'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(condition=models.Q(('residente__isnull', False), ('usuario__isnull', False), _connector='OR'), name='notificacion_destinatario_requerido'),
        ),
    ]
