# Generated by Django 5.2.6 on 2025-09-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_usuario_alter_notificacion_residente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='campania',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='broadcast_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.DeleteModel(
            name='NotificacionCampania',
        ),
    ]
