# Generated by Django 5.2.6 on 2025-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_seed_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='tipo',
            field=models.CharField(choices=[('UNIDADES', 'Por unidades (ej. churrasqueras)'), ('AFORO', 'Por capacidad/turnos')], max_length=10),
        ),
    ]
